### ISSUE TITLE
Swift Scarffolding Error 

### ISSUE THREAD

**Issue by mayyuen318** [SkygearIO/skygear-Scaffolding-iOS#16]
<img width="1273" alt="screen shot 2017-10-22 at 11 46 14 pm" src="https://user-images.githubusercontent.com/7130966/31863671-4f55d5de-b783-11e7-8848-3b4a308343b1.png">

Build failure becoz of the error shown in the picture.

**Comment by rickmak** [comment]
It is because scaffolding requires SKYKit 1.1 + but not specified in Podfile. Resulting in cocoapod only use the latest version available in local cache.

**Comment by rickmak** [comment]
Should be resolved via e4e9515
